name: raschet_gsm
description: Project raschet rashoda GSM for PA.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter     
  shared_preferences: ^2.1.2    
  animated_text_kit: ^4.2.2  
  path_provider: ^2.0.15
  path: ^1.8.0
  sqflite: ^2.2.8+4  
  dropdown_button2: ^2.3.7
  intl: ^0.18.0
  mask_text_input_formatter: ^2.5.0
  flutter_launcher_icons: ^0.13.1
  rflutter_alert: ^2.0.7
  url_launcher: ^6.1.14

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon3.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/baza.db
    - assets/fon.png  
    - assets/icon.png  
    - assets/icon1.png
    - assets/icon2.png
    - assets/OdiozSoft.png
    - assets/whatsapp.png
  fonts:
    - family: Evolventa
      fonts:
        - asset: assets/fonts/Evolventa-Regular.ttf
        - asset: assets/fonts/Evolventa-Bold.ttf
    #- family: RobotoCondensed
    #  fonts:
    #    - asset: assets/fonts/RobotoCondensed-Bold.ttf
    #    - asset: assets/fonts/RobotoCondensed-Regular.ttf